import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";

const ws = Work_Sans({
  weight: ['300', '400', '500', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ws.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
